name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build Dockerfile
        run: docker build -t devops-app .

      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag & and push image
        run: |
          docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app

      - name: Docker Run
        run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
